source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'EVReflection', :git => 'https://github.com/evermeer/EVReflection.git', :branch => 'Swift2'
#pod 'WhereAmI'
pod 'Async', :git => 'https://github.com/duemunk/Async.git', :branch => 'feature/Swift_2.0'
pod 'PermissionScope', :git => 'https://github.com/nickoneill/PermissionScope.git', :branch => 'swift2'


pod 'JSQMessagesViewController'
pod 'CRToast'
pod 'UIImage-Resize'
pod 'UzysAssetsPickerController'
pod 'VIPhotoView'
#pod 'SSASideMenu' --> for now included

