source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'RESideMenu'
pod 'JSQMessagesViewController'
pod 'CRToast'
pod 'CTAssetsPickerController'
pod 'UIImage-Resize'
pod 'WhereAmI'

# Will not work using a pod becauese public extensions are not supported in a framework. Just added the files to the project.
#pod 'ExSwift'

