source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'RESideMenu'
pod 'JSQMessagesViewController'
pod 'CRToast'
pod 'UIImage-Resize'
pod 'WhereAmI', '~> 1.1'
pod 'UzysAssetsPickerController'
pod 'VIPhotoView'

# Will not work using a pod becauese public extensions are not supported in a framework. Just added the files to the project.
#pod 'ExSwift'

